name: Build & Push

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Login to GHCR
        run: echo "${{ github.token }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build & push image with Buildpacks (Spring Boot plugin)
        run: |
          ./mvnw -B -DskipTests package spring-boot:build-image \
            -Dspring-boot.build-image.imageName=ghcr.io/hello-world-argocd-org/hello-world:${{ github.sha }}
          # also tag latest
          docker tag ghcr.io/hello-world-argocd-org/hello-world:${{ github.sha }} ghcr.io/hello-world-argocd-org/hello-world:latest
          docker push ghcr.io/hello-world-argocd-org/hello-world:${{ github.sha }}
          docker push ghcr.io/hello-world-argocd-org/hello-world:latest